osu-api:
    timeout: 3000
    rateLimit:
        tokensPerInterval: 60
        interval: minute

discord:
    webhook:
        id: 0
        secret: null
    errorLogWebhook:
        id: 0
        secret: null

http:
    # eiher a tcp-port-nr to listen on or a path to a unix-socket
    listen: ../http.sock

    # hostname/ip to listen on, '0.0.0.0' for all interfaces
    # ignored if using a unix-socket
    host: 0.0.0.0

    # chmod the socket after creation
    # ignored if not using unix-socket or if value is falsy
    socketChmod: 0666

dirs:
    data: data
    coverCache: coverCache
    tmp: tmp

redis:
    host: localhost
    port: 6379
    prefix: look-at-my-score

cacheTimes:
    get_beatmaps: 86400 # 24*60*60 ==> 24 hour
    get_scores: 300 #         5*60 ==> 5 min
    get_user_recent: 300 #    5*60 ==> 5 min

image-result-url: "{protocol}://{host}/score/{image-id}.png"

watermark:
    text: LookAtMySco.re
    underline-length: 88

log:
    dir: log
    level: info

resultTemplates:
  - id: 'result-direct-img-url'
    name: 'Direct image url'
    size: 'lg'
    template: '{imgage-url}'
  - id: 'result-bb-code'
    name: 'BBCode'
    size: 'sm'
    template: '[url={website-url}][img]{imgage-url}[/img][/url]'
  - id: 'result-markdown'
    name: 'Markdown'
    size: 'sm'
    template: '[![]({imgage-url})]({website-url})'
  - id: 'result-html'
    name: 'HTML'
    size: 'sm'
    template: '<a href="{website-url}"><img src="{imgage-url}"></a>'
