http:
    # eiher a tcp-port-nr to listen on or the value 'unix-socket' in which
    # case it will use the value of path.socketFile to listen on
    listen: unix-socket

    # hostname/ip to listen on, '0.0.0.0' for all interfaces
    # ignored if using 'unix-socket'
    host: 0.0.0.0

redis:
    host: localhost
    port: 6379
    prefix: look-at-my-score

cacheTimes:
    get_beatmaps: 86400 # 24*60*60 ==> 24 hour
    get_scores: 300 #         5*60 ==> 5 min

image-result-url: "{protocol}://{host}/score/{image-id}.png"

watermark:
    text: LookAtMySco.re
    underline-length: 88
