http:
    # eiher a tcp-port-nr to listen on or a path to a unix-socket
    listen: ../http.sock

    # hostname/ip to listen on, '0.0.0.0' for all interfaces
    # ignored if using a unix-socket
    host: 0.0.0.0

    # chmod the socket after creation
    # ignored if not using unix-socket or if value is falsy
    socketChmod: 0666

dirs:
    data: data
    coverCache: coverCache
    tmp: tmp

redis:
    host: localhost
    port: 6379
    prefix: look-at-my-score

cacheTimes:
    get_beatmaps: 86400 # 24*60*60 ==> 24 hour
    get_scores: 300 #         5*60 ==> 5 min

image-result-url: "{protocol}://{host}/score/{image-id}.png"

watermark:
    text: LookAtMySco.re
    underline-length: 88

gaCode: UA-44234598-3

log:
    dir: log
    level: info
